---
notifications:
  email:
    recipients:
      - knowledgejunkie@gmail.com

    on_success: always
    on_failure: always

sudo: required

language: bash

env:
  - release: debian_10
    distro: debian
    codename: buster
  - release: debian_11
    distro: debian
    codename: bullseye
  - release: debian_sid
    distro: debian
    codename: sid
  - release: ubuntu_1804_lts
    distro: ubuntu
    codename: bionic
  - release: ubuntu_1910
    distro: ubuntu
    codename: eoan
  - release: ubuntu_2004_lts
    distro: ubuntu
    codename: focal
  - release: centos_7
    distro: centos
    codename: 7
  - release: centos_8
    distro: centos
    codename: 8
  - release: fedora_31
    distro: fedora
    codename: 31
  - release: fedora_32
    distro: fedora
    codename: 32

branches:
  only:
    - master

services:
  - docker

before_install:
  - export TZ=Europe/London
  - date
  - env | sort
  - sudo apt-get update -qq

install:
  - sudo docker build -f .Dockerfile.${distro}-${codename} -t xmltv-build-deps/${distro}-${codename} .
  - sudo docker run -t --detach -v $TRAVIS_BUILD_DIR:/src --name xmltv xmltv-build-deps/${distro}-${codename} /bin/bash
  - sudo docker ps -a

script:
  - docker exec -it xmltv /bin/bash -c "cd /src && perl Makefile.PL --yes"
  - docker exec -it xmltv /bin/bash -c "cd /src && make"
  - docker exec -it xmltv /bin/bash -c "cd /src && make test"
